### ISSUE TITLE
Post-processing bug in night mode - black screen becomes grey

### ISSUE THREAD

**Issue by a--v--k** [dschuermann/document-viewer#15]
https://code.google.com/p/ebookdroid/issues/detail?id=426

The problem concerns decreesing brightness/contrast in night mode.
When tuning any of graphic postprocessing options to decrease minimal Super_AMOLED+ screen brightness - black screen background becomes grey and awfully eye hurting...

What is the expected output?
- I want to block postprocessing of background, only for text and picture layers.
- I want to tune text brightness increasing/decreasing via screen left border sliding, like it is implemented in the latest version of Cool Reader.
- I want to use minimal text brightness, less than such in android tray settings (see Cool Reader).

What version of the product are you using?
1.6.4

On what operating system?
Android 3

What device are you using?
Samsung Galaxy Tab 7.7

**Comment by tuxor1337** [comment]
Rejected upstream...
