### ISSUE TITLE
Перескок на первую страницу при пролистывании

### ISSUE THREAD

**Issue by a--v--k** [dschuermann/document-viewer#17]
https://code.google.com/p/ebookdroid/issues/detail?id=434

При прокрутке страницы иногда сбрасывает на первую страницу книги.
Баг возникает на книгах pdf и djvu форматов.

Версия 1.6.4 optimized for Cortex A8
Устройство Samsung Galaxy Note GT-N7000, Android 4.1.2, XXLSC

**Comment by tuxor1337** [comment]
This is actually a dup of #22
