### ISSUE TITLE
Color hue or saturation is off or washed out.

### ISSUE THREAD

**Issue by a--v--k** [dschuermann/document-viewer#18]
https://code.google.com/p/ebookdroid/issues/detail?id=437

What steps will reproduce the problem?
1. open a PDF with color images.
2.
3.

What is the expected output?
Colors are darker and detailed.

What do you see instead?
Colors are washed out and overexposed.

What version of the product are you using?
1.6.4

On what operating system?
4.1.1

What device are you using?
Galaxy Note 10.1

Please provide any additional information below.
The color rendition is off with multiple PDF files. I've tried several textbooks and while text is sharp, there is a color difference with the entire file. I've attached photos to illustrate what I am seeing.

I have tried adjusting the contrast, gamma, exposure for hours trying many combinations to get closer but all it does is wash it out more. Is there an unadjusted color scheme?

**Comment by tuxor1337** [comment]
Can be solved by using "slow cmyk to rgb" setting (see upstream).
