### ISSUE TITLE
Tap-on-screen submenus not properly accessible

### ISSUE THREAD

**Issue by a--v--k** [dschuermann/document-viewer#21]
https://code.google.com/p/ebookdroid/issues/detail?id=467

What steps will reproduce the problem?
После официального обновления Samsung Galaxy S2 до Android 4.1.2 Jelly Bean:
1. Во время просмотра PDF нажать кнопку меню или два раза тапнуть по экрану.
2. Появляется меню "Навигация, Вид, Настройки, О программе, Закрыть".
3. При нажатии на первые три пункта меню (Навигация, Вид, Настройки) на долю секунды появляется нужное меню и сразу пропадает. Пункты "О программе" и "Закрыть" работают нормально.

What is the expected output?
Меню навигации и настроек.

What do you see instead?
Ничего.

What version of the product are you using?
v 1.6.6

On what operating system?
официальный Android 4.1.2

What device are you using?
Samsung Galaxy S2

Please provide any additional information below.
Невозможность использовать меню в книге очень мешает. До этого программа была для меня лучшим и единственным PDF-ридером.

**Comment by tuxor1337** [comment]
Can't reproduce. Reopen with more accurate description if needed.

**Comment by a--v--k** [comment]
Little prompt: it is samsung-specific buf
