### ISSUE TITLE
Slow scrolling and rendering on Huawei Mediapad 10 FHD

### ISSUE THREAD

**Issue by a--v--k** [dschuermann/document-viewer#30]
https://code.google.com/p/ebookdroid/issues/detail?id=524

What steps will reproduce the problem?
1.Open any pdf or djvu document
2.See slow, laggy scrolling and slow page rendering. Much slower than on single core Xperia Arc phone.
3.

What is the expected output?
Maybe GPU acceleration used a wrong way, or Huawei GPU driver is not optimized. Maybe to add a setting for CPU-only (software) rendering and scrolling, or to repair the GPU rendering.

What do you see instead?

What version of the product are you using?

On what operating system?
Android 4.1.2, stock

What device are you using?
Huawei Mediapad 10 FHD, 1,4 GHz Cortex A9 CPU (Hisilicon K3V2), Vivante GC4000 GPU, 2 GB RAM.

Please provide any additional information below.
Feel free to contact me on e-mail, both russian and english. I can help you to test new versions.

**Comment by tuxor1337** [comment]
Rejected upstream ...
