### ISSUE TITLE
request: replace white in night mode with a different color

### ISSUE THREAD

**Issue by oligilo** [dschuermann/document-viewer#37]
I don't have much experience with programming, I'm more of a 'reader' and almost always I use the night mode for reading: it's easier on the eyes. However the white in the night mode is still too bright and contrasty for night reading and it would be very nice if one can change that text color to something less abrasive like beige or khaki. My brother is telling me that the process for getting into nightmode in this code (EbookDroid) is a series of loops that converts the document colors to their corresponding negative values (somehow) and its not straightforward to make the whites in nightmode to some other color like I mentioned. I would very much appreciate if you could consider this possibility as it really enhances the reading experience for those who do intensive reading on this app.

**Comment by tuxor1337** [comment]
There hasn't been any activity from the op in a while. Reopen if you don't like my suggestion.
