### ISSUE TITLE
Cyrillic fonts issue

### ISSUE THREAD

**Issue by klb3317** [dschuermann/document-viewer#49]
PDF with Cyrillic fonts are displayed incorrectly.
Please see screenshot attached.

![screenshot_2014-07-20-00-27-18](https://cloud.githubusercontent.com/assets/8211534/3635739/e9578422-0f87-11e4-9bda-657f9417cfcd.png)

**Comment by tuxor1337** [comment]
Can you point to an affected PDF that is freely available online, please?

**Comment by tuxor1337** [comment]
Closing for now due to missing "evidence". Reopen pointing to an affected pdf if needed.
