### ISSUE TITLE
Get support for cbr file format

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [dschuermann/document-viewer#58]
I found the author of Sumatra PDF have a decompression library, I think use this library can help you to get support cbr or more file formats. Here is his library: https://github.com/sumatrapdfreader/sumatrapdf/tree/master/ext/unarr

**Comment by KrasnayaPloshchad** [comment]
Here is the project's homepage: 
https://github.com/zeniko/unarr

**Comment by KrasnayaPloshchad** [comment]
By the way, I found another libraris to make use of. I want to recommend to you:

https://github.com/sumatrapdfreader/sumatrapdf/raw/master/AUTHORS

**Comment by tuxor1337** [comment]
SumatraPDF is based on pretty much the same libraries as document-viewer. At the moment nobody is really working on document-viewer. But maybe in a far future somebody will address all those issues that we have at the moment with document-viewer and maybe then, this somebody will add your desired cbr-support...

**Comment by tuxor1337** [comment]
By the way, I'm closing this for now, because there is already a report about comic formats: issue #5 ...

**Comment by KrasnayaPloshchad** [comment]
Thanks for your remind, I also found Domonik's advice, I hope this issue will be solved soon.

**Comment by KrasnayaPloshchad** [comment]
SumatraPDF have some valuable libraries that DV do not have, these may be helpful for other file formats.
