### ISSUE TITLE
App crashes for some PDF files

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [dschuermann/document-viewer#62]
Thanks to all devs, it is the most useful reader on android! :-)

When opening some PDF files, this app will crash, there is some files that make this app crash:

http://www.linuxlibertine.org/fileadmin/user_upload/PDF/Yggdrasil3-EN.pdf
http://www.linuxlibertine.org/fileadmin/user_upload/PDF/Yggdrasil3.pdf
https://www.huanghuagang.org/hhgLibrary/july2008/yan-an_riji.pdf

**Comment by tuxor1337** [comment]
Closing this, because it will be fixed once MuPDF is updated to the latest version and that's already targeted in issue #51
