### ISSUE TITLE
Problem with a particular PDF rendering text

### ISSUE THREAD

**Issue by baudtack** [dschuermann/document-viewer#65]
I'm having a problem using this pdf http://cdn.online-go.com/shape_up.pdf

When looking at say "Introduction: The scope of shape" the headings render fine but the text is entirely small boxes, as though it's unsure how to render the characters in question.

I'm running CM11.2 on a samsung galaxy s5 with Document Viewer and the font pack from f-droid.

Any ideas what I can try to fix this?

**Comment by tuxor1337** [comment]
Duplicate of #51 which is fixed already.

How to fix this? Build and install latest version from Github-Master. Can't tell at the moment, when we will be having a new release.

**Comment by baudtack** [comment]
Ok Thanks.
