### ISSUE TITLE
Update Google Play app also?

### ISSUE THREAD

**Issue by ebraminio** [dschuermann/document-viewer#78]
Hey guys, would you mind update [Document Viewer app on Google Play](https://play.google.com/store/apps/details?id=org.sufficientlysecure.viewer) also? I'm using the F-Droid version which have the patch I sent last year, I was using the custom build for having that even but after releasing the new version I was expecting I could finally download it directly from Google Play? Thank you

**Comment by tuxor1337** [comment]
Okay, I think @dschuermann has to look into this.

By the way, why are you so eager to have it in Google Play? Is something wrong about F-Droid?

**Comment by ebraminio** [comment]
I love F-Droid also, I have an app that is just available on F-Droid :-) However it lacks autoupdate (which implementing such feature needs root) and it is hard to learn the procedure of its installation to others.

**Comment by dschuermann** [comment]
k done :) should be available in some hours
